<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INADMYDOSHI1.local" name="com.axelerant.Assignment1" tests="8" failures="1" timestamp="06 Jun 2021 17:07:35 GMT" time="25.005" errors="0">
  <testcase name="paymentTransferAndVerifyTransactionDetails_TC003_002" time="2.675" classname="com.axelerant.Assignment1">
    <failure type="java.lang.AssertionError" message="NewlyCreated Acccount balance seems to be incorrect expected [$200.00] but found [$100.00]">
      <![CDATA[java.lang.AssertionError: NewlyCreated Acccount balance seems to be incorrect expected [$200.00] but found [$100.00]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.axelerant.Assignment1.paymentTransferAndVerifyTransactionDetails_TC003_002(Assignment1.java:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- paymentTransferAndVerifyTransactionDetails_TC003_002 -->
  <testcase name="paymentTransferAndVerifyTransactionDetails_TC003_002" time="3.671" classname="com.axelerant.Assignment1"/>
  <testcase name="paymentTransferAndVerifyTransactionDetails_TC003_001" time="1.291" classname="com.axelerant.Assignment1"/>
  <testcase name="verifyNewAccountOpening_TC001" time="3.348" classname="com.axelerant.Assignment1"/>
  <testcase name="verifyNewlyCreatedAccountDetails_TC002" time="4.307" classname="com.axelerant.Assignment1"/>
  <testcase name="verifyNewAccountOpening_TC001" time="3.382" classname="com.axelerant.Assignment1"/>
  <testcase name="verifyNewlyCreatedAccountDetails_TC002" time="2.717" classname="com.axelerant.Assignment1"/>
  <testcase name="loginTest" time="3.614" classname="com.axelerant.Assignment1"/>
</testsuite> <!-- com.axelerant.Assignment1 -->
